// Generated by scripts/generate-gps-policy-kotlin.mjs from mobile/contracts/v1/gps-policy.json.
// Do not edit by hand.
package us.ryanshores.atlas.mobile.shared.gps

internal data class GpsGoldenSample(
    val name: String,
    val accuracyMeters: Double,
    val ageMilliseconds: Long,
    val hasUsableFix: Boolean,
    val expectedQuality: String,
    val expectedAction: String,
)

internal data class GpsGoldenMovementSample(
    val distanceMeters: Double,
    val elapsedMilliseconds: Long,
    val previousAccuracyMeters: Double,
    val nextAccuracyMeters: Double,
    val expected: Boolean,
)

internal data class GpsGoldenSmoothingSample(
    val accuracyMeters: Double,
    val expectedWeight: Double,
)

internal object GpsPolicyGoldenFixtures {
    const val goodAccuracyMeters = 25.0
    const val fairAccuracyMeters = 75.0
    const val maxUsableAccuracyMeters = 100.0
    const val maxFixAgeMilliseconds = 15000L

    val samples = listOf(
        GpsGoldenSample(
            name = "firstCoarseFixWaits",
            accuracyMeters = 4000.0,
            ageMilliseconds = 0L,
            hasUsableFix = false,
            expectedQuality = "unusable",
            expectedAction = "wait-for-accurate-fix",
        ),
        GpsGoldenSample(
            name = "goodFixStartsRide",
            accuracyMeters = 12.0,
            ageMilliseconds = 0L,
            hasUsableFix = false,
            expectedQuality = "good",
            expectedAction = "use-fix",
        ),
        GpsGoldenSample(
            name = "fairFixIsAccepted",
            accuracyMeters = 75.0,
            ageMilliseconds = 0L,
            hasUsableFix = true,
            expectedQuality = "fair",
            expectedAction = "use-fix",
        ),
        GpsGoldenSample(
            name = "poorFixIsAcceptedButNotGuidancePrecise",
            accuracyMeters = 100.0,
            ageMilliseconds = 0L,
            hasUsableFix = true,
            expectedQuality = "poor",
            expectedAction = "use-fix",
        ),
        GpsGoldenSample(
            name = "laterCoarseFixKeepsLast",
            accuracyMeters = 4000.0,
            ageMilliseconds = 0L,
            hasUsableFix = true,
            expectedQuality = "unusable",
            expectedAction = "keep-last-fix",
        ),
        GpsGoldenSample(
            name = "staleFixKeepsLast",
            accuracyMeters = 12.0,
            ageMilliseconds = 15001L,
            hasUsableFix = true,
            expectedQuality = "unusable",
            expectedAction = "keep-last-fix",
        ),
        GpsGoldenSample(
            name = "negativeAccuracyKeepsLast",
            accuracyMeters = -1.0,
            ageMilliseconds = 0L,
            hasUsableFix = true,
            expectedQuality = "unusable",
            expectedAction = "keep-last-fix",
        ),
        GpsGoldenSample(
            name = "negativeAgeWaits",
            accuracyMeters = 12.0,
            ageMilliseconds = -1L,
            hasUsableFix = false,
            expectedQuality = "unusable",
            expectedAction = "wait-for-accurate-fix",
        ),
    )

    val plausibleMovementSamples = listOf(
        GpsGoldenMovementSample(
            distanceMeters = 45.0,
            elapsedMilliseconds = 2000L,
            previousAccuracyMeters = 10.0,
            nextAccuracyMeters = 12.0,
            expected = true,
        ),
        GpsGoldenMovementSample(
            distanceMeters = 1000.0,
            elapsedMilliseconds = 2000L,
            previousAccuracyMeters = 10.0,
            nextAccuracyMeters = 12.0,
            expected = false,
        ),
        GpsGoldenMovementSample(
            distanceMeters = -1.0,
            elapsedMilliseconds = 2000L,
            previousAccuracyMeters = 10.0,
            nextAccuracyMeters = 12.0,
            expected = false,
        ),
        GpsGoldenMovementSample(
            distanceMeters = 0.0,
            elapsedMilliseconds = 0L,
            previousAccuracyMeters = 10.0,
            nextAccuracyMeters = 12.0,
            expected = false,
        ),
    )

    val smoothingSamples = listOf(
        GpsGoldenSmoothingSample(
            accuracyMeters = 10.0,
            expectedWeight = 0.82,
        ),
        GpsGoldenSmoothingSample(
            accuracyMeters = 65.0,
            expectedWeight = 0.62,
        ),
        GpsGoldenSmoothingSample(
            accuracyMeters = 90.0,
            expectedWeight = 0.45,
        ),
    )
}
